### ISSUE TITLE
Question on preprocessing of inputs for neural network

### ISSUE THREAD

**Issue by FritzPeleke** [flag0010/pop_gen_cnn#5]
Hi, @flag0010 ,
I just read a blog "Exploring DNA with Deep Learning" by Charlie Harrington. In the blog, he reported that you explained that you aligned the sequences like one under another and retained just the regions "columns" with mutations. Then one-hot encoded this. 
I am a master student and have a research project to build a neural network that can identify the origin(continent) of a herpes virus from the DNA sequence. So far I've been learning Machine learning with like data already in CSV format which is easy to read and manipulate. It is my first work with DNA sequences and they are extremely long 'strings'.
My question is how did you align these sequences such that they are in a row by column form before getting the regions with variations. and when you talk of one-hot encoding did you make use of the sklearn's one-hot encoding class for example? I would really appreciate your expert help :)

**Comment by flag0010** [comment]
Hi Fritz.  We used simulations, which makes it unnecessary to align the DNA sequences.  However if you have real DNA samples you probably have 2 options.  One is to align all your sequences to a common reference genome using a reference based aligner.  The second is to perform multi-sequence alignment.  This page lists lots of software for either approach: https://en.wikipedia.org/wiki/List_of_sequence_alignment_software

As far as one-hot encoding, the simulation software we used did it automatically.  I'm pretty sure you could also use sklearns one-hot method.  One watch out is that you probably want to focus on biallelic sites only.  If you have sites with > 2 alleles, the one-hot encoder should split them into extra columns, which may not be what you want as it will give them extra weight (though I think you could try it out that way and see how it performs).

Finally, you may want to check out this recent preprint: https://www.biorxiv.org/content/10.1101/2019.12.11.872051v1
They describe a method that sounds very similar to your question with herpes virus.
