### ISSUE TITLE
Version Specification

### ISSUE THREAD

**Issue by daki7711** [flag0010/pop_gen_cnn#6]
Both tensorflow and keras has upgraded that if you naively install by using the command "pip install keras" and "conda install tensorflow" these code will not work. Instead it works when you install "pip install keras==2.0.0" and "conda install tensorflow==1.15". So the readme file should change a bit

**Comment by flag0010** [comment]
i believe you are referencing this file: https://github.com/flag0010/pop_gen_cnn/blob/master/tajimas_D/README.md

it has been updated. https://github.com/flag0010/pop_gen_cnn/commit/f80ada84af0ac5dda10386ceec8a0ee6fc4ffbfe

**Comment by daki7711** [comment]
Thanks a lot.

It seems that this version of keras and tensorflow also works for the other files too.
